name: Audit Homebrew Repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM UTC
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup hombrew tap
        run: |
          brew tap commure/packages ./
      - name: Update homebrew
        run: |
          brew update
      - name: Run brew audit
        run: |
          brew audit --strict --online --tap ${{ github.repository }}
